name: emojicloud
description: A new Flutter package for vector emoji using emojicloud.
version: 1.0.0
homepage: https://github.com/ChangJoo-Park/flutter_emojicloud
repository: https://github.com/ChangJoo-Park/flutter_emojicloud

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/svg/