import 'package:flutter/material.dart';
import 'package:emojicloud/emojicloud.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'EmojiCloud example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double size = 24;

  final emojis = [
    EmojiCloud.airplane,
    EmojiCloud.angryFace,
    EmojiCloud.anguishedFace,
    EmojiCloud.anxiousFaceWithSweat,
    EmojiCloud.astonishedFace,
    EmojiCloud.avocado,
    EmojiCloud.backhandIndexPointingDownSkin1,
    EmojiCloud.backhandIndexPointingDownSkin2,
    EmojiCloud.backhandIndexPointingDownSkin3,
    EmojiCloud.backhandIndexPointingDownSkin4,
    EmojiCloud.backhandIndexPointingDownSkin5,
    EmojiCloud.backhandIndexPointingDown,
    EmojiCloud.backhandIndexPointingLeftSkin1,
    EmojiCloud.backhandIndexPointingLeftSkin2,
    EmojiCloud.backhandIndexPointingLeftSkin3,
    EmojiCloud.backhandIndexPointingLeftSkin4,
    EmojiCloud.backhandIndexPointingLeftSkin5,
    EmojiCloud.backhandIndexPointingLeft,
    EmojiCloud.backhandIndexPointingRightSkin1,
    EmojiCloud.backhandIndexPointingRightSkin2,
    EmojiCloud.backhandIndexPointingRightSkin3,
    EmojiCloud.backhandIndexPointingRightSkin4,
    EmojiCloud.backhandIndexPointingRightSkin5,
    EmojiCloud.backhandIndexPointingRight,
    EmojiCloud.backhandIndexPointingUpSkin1,
    EmojiCloud.backhandIndexPointingUpSkin2,
    EmojiCloud.backhandIndexPointingUpSkin3,
    EmojiCloud.backhandIndexPointingUpSkin4,
    EmojiCloud.backhandIndexPointingUpSkin5,
    EmojiCloud.backhandIndexPointingUp,
    EmojiCloud.baltasar,
    EmojiCloud.banana,
    EmojiCloud.beachWithUmbrella,
    EmojiCloud.beach,
    EmojiCloud.beamingFaceWithSmilingEyes,
    EmojiCloud.bell,
    EmojiCloud.bicycle,
    EmojiCloud.brokenHeart,
    EmojiCloud.bubbles,
    EmojiCloud.calendar,
    EmojiCloud.callMeHandSkin1,
    EmojiCloud.callMeHandSkin2,
    EmojiCloud.callMeHandSkin3,
    EmojiCloud.callMeHandSkin4,
    EmojiCloud.callMeHandSkin5,
    EmojiCloud.callMeHand,
    EmojiCloud.camera,
    EmojiCloud.cat,
    EmojiCloud.checkMark,
    EmojiCloud.clappingHandsSkin1,
    EmojiCloud.clappingHandsSkin2,
    EmojiCloud.clappingHandsSkin3,
    EmojiCloud.clappingHandsSkin4,
    EmojiCloud.clappingHandsSkin5,
    EmojiCloud.clappingHands,
    EmojiCloud.clock,
    EmojiCloud.clownFace,
    EmojiCloud.coldFace,
    EmojiCloud.compass,
    EmojiCloud.confoundedFace,
    EmojiCloud.cool,
    EmojiCloud.cowboyHatFace,
    EmojiCloud.crossedFingersSkin1,
    EmojiCloud.crossedFingersSkin2,
    EmojiCloud.crossedFingersSkin3,
    EmojiCloud.crossedFingersSkin4,
    EmojiCloud.crossedFingersSkin5,
    EmojiCloud.crossedFingers,
    EmojiCloud.cryingFace,
    EmojiCloud.crystalBall,
    EmojiCloud.dissapointedFace,
    EmojiCloud.dizzyFace,
    EmojiCloud.dog,
    EmojiCloud.downcastFaceWithSweat,
    EmojiCloud.droolingFace,
    EmojiCloud.eggplant,
    EmojiCloud.envelope,
    EmojiCloud.explodingHead,
    EmojiCloud.expressiolessFace,
    EmojiCloud.faceBlowingAKiss,
    EmojiCloud.faceSavoringFood,
    EmojiCloud.faceScreamingInFear,
    EmojiCloud.faceWithHandOverMouth,
    EmojiCloud.faceWithHeadBandage,
    EmojiCloud.faceWithMedicalMask,
    EmojiCloud.faceWithMonocle,
    EmojiCloud.faceWithOpenMouth,
    EmojiCloud.faceWithRaisedEyebrow,
    EmojiCloud.faceWithRollingEyes,
    EmojiCloud.faceWithSteamFromNose,
    EmojiCloud.faceWithSymbolsOnMouth,
    EmojiCloud.faceWithTearsOfJoy,
    EmojiCloud.faceWithThermometer,
    EmojiCloud.faceWithTongue,
    EmojiCloud.faceWithoutMouth,
    EmojiCloud.fearfulFace,
    EmojiCloud.fire,
    EmojiCloud.flushedFace,
    EmojiCloud.foldedHandsSkin1,
    EmojiCloud.foldedHandsSkin2,
    EmojiCloud.foldedHandsSkin3,
    EmojiCloud.foldedHandsSkin4,
    EmojiCloud.foldedHandsSkin5,
    EmojiCloud.foldedHands,
    EmojiCloud.free,
    EmojiCloud.frowningFaceWithOpenMouth,
    EmojiCloud.frowningFace,
    EmojiCloud.gaspar,
    EmojiCloud.gemstone,
    EmojiCloud.glasses,
    EmojiCloud.greenApple,
    EmojiCloud.grimacingFace,
    EmojiCloud.grinningFaceWithBigEyes,
    EmojiCloud.grinningFaceWithSweat,
    EmojiCloud.grinningFace1,
    EmojiCloud.grinningFace,
    EmojiCloud.grinningSquintingFace,
    EmojiCloud.hamburger,
    EmojiCloud.handWithFingersSplayedSkin1,
    EmojiCloud.handWithFingersSplayedSkin2,
    EmojiCloud.handWithFingersSplayedSkin3,
    EmojiCloud.handWithFingersSplayedSkin4,
    EmojiCloud.handWithFingersSplayedSkin5,
    EmojiCloud.handWithFingersSplayed,
    EmojiCloud.handshakeSkin1,
    EmojiCloud.handshakeSkin2,
    EmojiCloud.handshakeSkin3,
    EmojiCloud.handshakeSkin4,
    EmojiCloud.handshakeSkin5,
    EmojiCloud.handshake,
    EmojiCloud.heart,
    EmojiCloud.highVoltage,
    EmojiCloud.hotFace,
    EmojiCloud.house,
    EmojiCloud.huggingFace,
    EmojiCloud.hushedFace,
    EmojiCloud.indexPointingUpSkin1,
    EmojiCloud.indexPointingUpSkin2,
    EmojiCloud.indexPointingUpSkin3,
    EmojiCloud.indexPointingUpSkin4,
    EmojiCloud.indexPointingUpSkin5,
    EmojiCloud.indexPointingUp,
    EmojiCloud.joker,
    EmojiCloud.kissingFaceWithClosedEyes,
    EmojiCloud.kissingFaceWithSmilingEyes,
    EmojiCloud.kissingFace,
    EmojiCloud.kiwi,
    EmojiCloud.landmark,
    EmojiCloud.leftFacingFistSkin1,
    EmojiCloud.leftFacingFistSkin2,
    EmojiCloud.leftFacingFistSkin3,
    EmojiCloud.leftFacingFistSkin4,
    EmojiCloud.leftFacingFistSkin5,
    EmojiCloud.leftFacingFist,
    EmojiCloud.lion,
    EmojiCloud.loudlyCryingFace,
    EmojiCloud.loveYouGestureSkin1,
    EmojiCloud.loveYouGestureSkin2,
    EmojiCloud.loveYouGestureSkin3,
    EmojiCloud.loveYouGestureSkin4,
    EmojiCloud.loveYouGestureSkin5,
    EmojiCloud.loveYouGesture,
    EmojiCloud.lyingFace,
    EmojiCloud.mailbox,
    EmojiCloud.melchor,
    EmojiCloud.middleFingerSkin1,
    EmojiCloud.middleFingerSkin2,
    EmojiCloud.middleFingerSkin3,
    EmojiCloud.middleFingerSkin4,
    EmojiCloud.middleFingerSkin5,
    EmojiCloud.middleFinger,
    EmojiCloud.moneyMouthFaceBitcoin,
    EmojiCloud.moneyMouthFaceDollar,
    EmojiCloud.moneyMouthFaceEuro,
    EmojiCloud.moneyMouthFacePound,
    EmojiCloud.moneyMouthFaceRuble,
    EmojiCloud.moneyMouthFaceYen,
    EmojiCloud.monkey,
    EmojiCloud.nauseatedFace,
    EmojiCloud.nerdFace,
    EmojiCloud.neutralFace,
    EmojiCloud.okHandSkin1,
    EmojiCloud.okHandSkin2,
    EmojiCloud.okHandSkin3,
    EmojiCloud.okHandSkin4,
    EmojiCloud.okHandSkin5,
    EmojiCloud.okHand,
    EmojiCloud.ok,
    EmojiCloud.oncomingFistSkin1,
    EmojiCloud.oncomingFistSkin2,
    EmojiCloud.oncomingFistSkin3,
    EmojiCloud.oncomingFistSkin4,
    EmojiCloud.oncomingFistSkin5,
    EmojiCloud.oncomingFist,
    EmojiCloud.openHandsSkin1,
    EmojiCloud.openHandsSkin2,
    EmojiCloud.openHandsSkin3,
    EmojiCloud.openHandsSkin4,
    EmojiCloud.openHandsSkin5,
    EmojiCloud.openHands,
    EmojiCloud.palm,
    EmojiCloud.palmsUpTogetherSkin1,
    EmojiCloud.palmsUpTogetherSkin2,
    EmojiCloud.palmsUpTogetherSkin3,
    EmojiCloud.palmsUpTogetherSkin4,
    EmojiCloud.palmsUpTogetherSkin5,
    EmojiCloud.palmsUpTogether,
    EmojiCloud.panda,
    EmojiCloud.partyPopper,
    EmojiCloud.partyingFace,
    EmojiCloud.peach,
    EmojiCloud.pencil,
    EmojiCloud.pensiveFace,
    EmojiCloud.pileOfPoo,
    EmojiCloud.pinchHandSkin1,
    EmojiCloud.pinchHandSkin2,
    EmojiCloud.pinchHandSkin3,
    EmojiCloud.pinchHandSkin4,
    EmojiCloud.pinchHandSkin5,
    EmojiCloud.pinchHand,
    EmojiCloud.pinchedFingersSkin1,
    EmojiCloud.pinchedFingersSkin2,
    EmojiCloud.pinchedFingersSkin3,
    EmojiCloud.pinchedFingersSkin4,
    EmojiCloud.pinchedFingersSkin5,
    EmojiCloud.pinchedFingers,
    EmojiCloud.pizza,
    EmojiCloud.pleadingFace,
    EmojiCloud.poutingFace,
    EmojiCloud.rainbow,
    EmojiCloud.raisedBackOfHandSkin1,
    EmojiCloud.raisedBackOfHandSkin2,
    EmojiCloud.raisedBackOfHandSkin3,
    EmojiCloud.raisedBackOfHandSkin4,
    EmojiCloud.raisedBackOfHandSkin5,
    EmojiCloud.raisedBackOfHand,
    EmojiCloud.raisedFistSkin1,
    EmojiCloud.raisedFistSkin2,
    EmojiCloud.raisedFistSkin3,
    EmojiCloud.raisedFistSkin4,
    EmojiCloud.raisedFistSkin5,
    EmojiCloud.raisedFist,
    EmojiCloud.raisedHandSkin1,
    EmojiCloud.raisedHandSkin2,
    EmojiCloud.raisedHandSkin3,
    EmojiCloud.raisedHandSkin4,
    EmojiCloud.raisedHandSkin5,
    EmojiCloud.raisedHand,
    EmojiCloud.raisingHandsSkin1,
    EmojiCloud.raisingHandsSkin2,
    EmojiCloud.raisingHandsSkin3,
    EmojiCloud.raisingHandsSkin4,
    EmojiCloud.raisingHandsSkin5,
    EmojiCloud.raisingHands,
    EmojiCloud.recyclingSymbol,
    EmojiCloud.redApple,
    EmojiCloud.relievedFace,
    EmojiCloud.rightFacingFistSkin1,
    EmojiCloud.rightFacingFistSkin2,
    EmojiCloud.rightFacingFistSkin3,
    EmojiCloud.rightFacingFistSkin4,
    EmojiCloud.rightFacingFistSkin5,
    EmojiCloud.rightFacingFist,
    EmojiCloud.robot,
    EmojiCloud.rocket,
    EmojiCloud.rollingOnTheFloorLaughing,
    EmojiCloud.roundPushpin,
    EmojiCloud.sadButRelievedFace,
    EmojiCloud.santaClaus,
    EmojiCloud.scrunchedFace,
    EmojiCloud.shushingFace,
    EmojiCloud.signOfTheHornsSkin1,
    EmojiCloud.signOfTheHornsSkin2,
    EmojiCloud.signOfTheHornsSkin3,
    EmojiCloud.signOfTheHornsSkin4,
    EmojiCloud.signOfTheHornsSkin5,
    EmojiCloud.signOfTheHorns,
    EmojiCloud.sleepFace,
    EmojiCloud.sleepyFace,
    EmojiCloud.slightlyFrowningFace,
    EmojiCloud.slightlySmilingFace,
    EmojiCloud.smilingFaceWithHalo,
    EmojiCloud.smilingFaceWithHeartEyes,
    EmojiCloud.smilingFaceWithHearts,
    EmojiCloud.smilingFaceWithSmilingEyes,
    EmojiCloud.smilingFaceWithSunglasses,
    EmojiCloud.smilingFace,
    EmojiCloud.smirkingFace,
    EmojiCloud.sneezingFace,
    EmojiCloud.sparkles,
    EmojiCloud.squintingFaceWithTongue,
    EmojiCloud.starStruck,
    EmojiCloud.star,
    EmojiCloud.sweatDroplets,
    EmojiCloud.thinkingFace,
    EmojiCloud.thumbsDownSkin1,
    EmojiCloud.thumbsDownSkin2,
    EmojiCloud.thumbsDownSkin3,
    EmojiCloud.thumbsDownSkin4,
    EmojiCloud.thumbsDownSkin5,
    EmojiCloud.thumbsDown,
    EmojiCloud.thumbsUpSkin1,
    EmojiCloud.thumbsUpSkin2,
    EmojiCloud.thumbsUpSkin3,
    EmojiCloud.thumbsUpSkin4,
    EmojiCloud.thumbsUpSkin5,
    EmojiCloud.thumbsUp,
    EmojiCloud.tiredFace,
    EmojiCloud.umbrellaWithRainDrops,
    EmojiCloud.unamusedFace,
    EmojiCloud.unicorn,
    EmojiCloud.upsideDownFace,
    EmojiCloud.victoryHandSkin1,
    EmojiCloud.victoryHandSkin2,
    EmojiCloud.victoryHandSkin3,
    EmojiCloud.victoryHandSkin4,
    EmojiCloud.victoryHandSkin5,
    EmojiCloud.victoryHand,
    EmojiCloud.vomitingFace,
    EmojiCloud.vulcanSaluteSkin1,
    EmojiCloud.vulcanSaluteSkin2,
    EmojiCloud.vulcanSaluteSkin3,
    EmojiCloud.vulcanSaluteSkin4,
    EmojiCloud.vulcanSaluteSkin5,
    EmojiCloud.vulcanSalute,
    EmojiCloud.wavingHandSkin1,
    EmojiCloud.wavingHandSkin2,
    EmojiCloud.wavingHandSkin3,
    EmojiCloud.wavingHandSkin4,
    EmojiCloud.wavingHandSkin5,
    EmojiCloud.wavingHand,
    EmojiCloud.wearyFace,
    EmojiCloud.weather,
    EmojiCloud.winkingFaceWithTongue,
    EmojiCloud.winkingFace,
    EmojiCloud.woozyFace,
    EmojiCloud.worriedFace1,
    EmojiCloud.worriedFace,
    EmojiCloud.writingHandSkin1,
    EmojiCloud.writingHandSkin2,
    EmojiCloud.writingHandSkin3,
    EmojiCloud.writingHandSkin4,
    EmojiCloud.writingHandSkin5,
    EmojiCloud.writingHand,
    EmojiCloud.xmasBall,
    EmojiCloud.xmasTree,
    EmojiCloud.yawningFace,
    EmojiCloud.zanyFace,
    EmojiCloud.zipperMouthFace,
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Container(
          height: MediaQuery.of(context).size.height,
          child: Stack(
            children: [
              SingleChildScrollView(
                child: Wrap(
                  children: emojis
                      .map(
                        (e) => GestureDetector(
                          onTap: () {
                            ScaffoldMessenger.of(context).clearSnackBars();
                            final filename =
                                e.replaceAll('.svg', '').split('/');
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                  content: Text(filename.last),
                                  duration: const Duration(seconds: 1)),
                            );
                          },
                          child: SvgPicture.asset(
                            e,
                            package: 'emojicloud',
                            width: size,
                            height: size,
                          ),
                        ),
                      )
                      .toList(),
                ),
              ),
              Positioned(
                bottom: 0,
                right: 0,
                child: Center(
                  child: ButtonBar(
                    children: [
                      TextButton(
                        child: const Text('Small'),
                        onPressed: () {
                          size = 24;
                          setState(() {});
                        },
                      ),
                      TextButton(
                        child: const Text('Medium'),
                        onPressed: () {
                          size = 64;
                          setState(() {});
                        },
                      ),
                      TextButton(
                        child: const Text('Large'),
                        onPressed: () {
                          size = 128;
                          setState(() {});
                        },
                      )
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
